source 'http://rubygems.org'

gem 'emojidex'
gem 'emojidex-converter', path: '../../emojidex-converter'
#gem 'emojidex-vectors', github: 'emojidex/emojidex-vectors'
gem 'emojidex-vectors', path: '../../emojidex-vectors'
