source 'http://rubygems.org'

gem 'emojidex', '0.0.23'
gem 'rapngasm', github: 'apngasm/rapngasm'
gem 'emojidex-converter', path: '../../emojidex-converter'
#gem 'emojidex-vectors', github: 'emojidex/emojidex-vectors'
gem 'emojidex-vectors', path: '../../emojidex-vectors'
