source 'http://rubygems.org'

gem 'emojidex', '~> 0.3.4'
gem 'rapngasm', '~> 3.2.0'
gem 'emojidex-converter', path: '../../emojidex-converter' #'~> 0.3.0'
gem 'emojidex-vectors', path: '../../emojidex-vectors'
